### ISSUE TITLE
Planarity issues with SRM

### ISSUE THREAD

**Issue by drlemmus** [MRC-LMB-ComputationalStructuralBiology/monomers#23]
Forwarding from Dale E.T. (edited):
//
I was looking over 7np8 in the PDB and comparing the deposited model to the PDB-REDO model.  It looks to me that REDO has refined the model with a problematic set of restraints. This group is a "siroheme" https://en.wikipedia.org/wiki/Siroheme

The atoms C2B and C3A are sp3 hybridized since they have a hydrogen atoms as a fourth ligand, but it looks pretty clear that the restraints don't believe in the hydrogen atoms and it restraining them as sp2. This seriously affects the conformations of the substitutes of these ringlets of the macrocycle.
//
Indeed the restraints for SRM seem inconsistent with the density, but as this compound is not compatible with AceDRG is cannot change it. Could you have a look?

**Comment by GaribMurshudov** [comment]
thank you. I am sure that there are number of such cases. At least for HEME like structures we sould be able to do better. I had one algorithm in my mind. But somebody needs to implement it. Algorithm is like this:
For heam like structurs:
1) Remove metal (in this case metal)
2) Change charge of N atoms that have two single bonds to -1 (it is just a trick not reflecting reality)
3) Generate restraints without Fe
4) bring back Fe into the dictionary generated by acedrg and to the pdb file. Position of Fe should be average of four N atoms
5) Put distance restraints (around 1.95 or 2A)
6) Put angle restraints. It can be done by checking N atoms. We need two angles 180 and four 90 degrees. Procedure should work without this step
7) Optimise PDB file with the new dictionary
8) Update coordinates in the cif file 

This should produce reasonable restraints for heam like structures. There are several hundred of them. I had a list of them. I can try to find that list.

**Comment by GaribMurshudov** [comment]
is the structure in CCD correct? As it is Fe must have +4. In the example 2V4J it looks like that there must at least +1 added to FE.  which would make Fe+5 at least. Is this correct?
if the bonding pattern given on RCSB then all N atoms must have -1. which makes Fe at least +4. and then environment dependence will add +1 or +2. 

https://www.rcsb.org/ligand/SRM

with other heam like structures usually Fe+2 on heam and some additional ligands make it +4 or something like that.
wikipedia structure looks correct (Fe+2 and in 2VDJ it would become at least +3)

Now question is: should we correct SRM in CCD also?

**Comment by GaribMurshudov** [comment]
My current conclusion: SRM in CCD is incorrect. Somebody needs to make bonding pattern for SRM. I can do it but I can do it next week.

**Comment by GaribMurshudov** [comment]
[srm_m.tgz](https://github.com/MRC-LMB-ComputationalStructuralBiology/monomers/files/10995825/srm_m.tgz)
Can you try this. If it is suitable then CCD should be made aware that their version of SRM is not correct and should be corrected.
In the cif file there are -1 on NC and ND. It should not harm refinement, but before putting these into the monomer library they will need to be corrected

**Comment by drlemmus** [comment]
Yes much better. I'll inform the PDB that the definition of SRM is incorrect

**Comment by GaribMurshudov** [comment]
Could you please keep me in the loop. I would like this and other ligand problems in the CCD to be sorted soon.

**Comment by ff95688469** [comment]
koou!

**Comment by GaribMurshudov** [comment]
Have fixed this and should it be closed?

**Comment by keitaroyam** [comment]
What is the PDB's decision?

**Comment by GaribMurshudov** [comment]
I have not heard anything from them. We need to fix on our side.
Perhaps I should chase this. We can talk about this on 15th.

**Comment by drlemmus** [comment]
The compound was updated in November last year, but no one was told. Please check whether the update was satisfactory so this issue may be closed.
