### ISSUE TITLE
Starting coordinates and restraints for HEO

### ISSUE THREAD

**Issue by drlemmus** [MRC-LMB-ComputationalStructuralBiology/monomers#36]
This came up at the Cold Spring Harbor Course for crystallography: the starting coordinates for HEO are pretty garbled. They clean up quite nicely when you idealise the coordinates, but the iron gets pouched out of the plane.

**Comment by keitaroyam** [comment]
It perhaps became a seasonal tradition.. https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2210&L=CCP4BB&P=R104954
Of course we should fix it. Some were fixed after this ccp4bb post by the way: https://github.com/MonomerLibrary/monomers/pull/8

**Comment by GaribMurshudov** [comment]
I think we need to sort out all heam like structures. There are errors in them in CCD (e.g. HEO, atom NB and ND have +1 charge on them. They also have double and single bonds. If this would be like that then FE would fly. On the other hand NB and NC are neutral.
These problems cause additional problems. 
I think all heam like structures (around 66 of them) should be checked and update in our monomer library and in the CCD. (SRM was just one of the problems which pdb has not correted yet)

**Comment by drlemmus** [comment]
Were the issues with CCD entries listed in the wiki communicated with the PDB?

**Comment by keitaroyam** [comment]
Yes, it was sent yesterday. I'd appreciate it if you could have a look at the update-metals branch.

**Comment by GaribMurshudov** [comment]
I thought #23 and #36 have been sorted out long time ago.
