### ISSUE TITLE
Big issue with atom nomenclature

### ISSUE THREAD

**Issue by drlemmus** [MRC-LMB-ComputationalStructuralBiology/monomers#39]
Because of the recent reannotation of amino-acid-like compounds, a lot of residues have changed atom names (ABU and PYR were the first ones I encountered). The whole monomer library needs to be checked against the current atom names in the Chemical Component Dictionary.

**Comment by keitaroyam** [comment]
Yes, we are aware of this. The plan is to change atom names in them, and keep old names as `_chem_comp_atom.alt_atom_id`. In this way we can also support model files with old atom names (gemmi already support this). An example could be found: https://github.com/MonomerLibrary/monomers/pull/37 @wojdyr

**Comment by drlemmus** [comment]
The sooner the better, literally thousands of pdb-redo databank updates fail because of this

**Comment by wojdyr** [comment]
yes, 635 monomers are going to be updated
