### ISSUE TITLE
chi5 in ARG is off

### ISSUE THREAD

**Issue by drlemmus** [MRC-LMB-ComputationalStructuralBiology/monomers#56]
The chi5 torsion in ARG is set to 0.00 with periodicity 2. That does not follow the standard in the sense that the NH2 is defined to be opposite the CD (_E_) and the NH1 is at the same side of CD (_Z_). So the default angle should be 180 and, since this bond is not freely rotatable, should have a periodicity of 1.

**Comment by keitaroyam** [comment]
While I agree that the ideal torsion angle should be 180 rather than 0, allowing periodicity 2 for such symmetric side chains could be beneficial. This way, we wouldn't need to pre-process the model to fix the nomenclature before refinement.

**Comment by drlemmus** [comment]
That only works because the assumption is that the NE CZ NH1 and NE CZ NH2 angles are the same. This is true in the restraints made by AceDRG, but not for other restraint targets that take the _E/Z_ difference into account. In the end it is a design choice, I suppose.

**Comment by drlemmus** [comment]
I can do the preprocessing in flipper so this issue can be closed.
